"""initial

Revision ID: 16ff47b418aa
Revises: 
Create Date: 2026-05-15 08:45:58.943176
"""
from alembic import op
import sqlalchemy as sa


revision = '16ff47b418aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('FILE', 'URL', name='source_type'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('current_stage', sa.Enum('FETCH', 'TRANSCRIBE', 'SEGMENT', 'CUT', 'THUMBNAIL', 'METADATA', 'UPLOAD', 'DONE', name='stage'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.LargeBinary(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript_excerpt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CUT', 'THUMBNAIL_READY', 'METADATA_READY', 'UPLOADED', 'FAILED', name='segment_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('SOURCE', 'TRANSCRIPT', 'SEGMENT', 'THUMBNAIL', name='asset_kind'), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('mime', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=255), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('youtube_title', sa.Text(), nullable=True),
    sa.Column('youtube_description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'UPLOADED', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    op.drop_table('assets')
    op.drop_table('segments')
    op.drop_table('youtube_accounts')
    op.drop_table('jobs')
    # ### end Alembic commands ###
